# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 986a99ccc3f7eed02e68dec5e096e5bea16137f90a72317eb500c3952e3312cae616367a25a006282c1b78dfa7a363c5b6c02cd16fe0db7afaa2d4558fa122e4

test:
  secret_key_base: d52257f7d3b529935bacc4e626d79433b1e904d41690f0b5cf24bce8a63a393c873bb1031096e5cd65daae14f5554f2ab7ceca061aa19f118d41a9f34965a92e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
